services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"  # For SSL
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx/conf.d/default.prod.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot
      - ./nginx/logs:/var/log/nginx  # For logs
    depends_on:
      - wordpress
    networks:
      - wordpress_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - wordpress_data:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    env_file:
      - .env
    networks:
      - wordpress_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  wordpress_network:
    driver: bridge

volumes:
  wordpress_data:
    driver: local 