FROM wordpress:php8.2-fpm-alpine

# Install required dependencies and PHP extensions
RUN set -ex; \
    \
    apk add --no-cache \
        $PHPIZE_DEPS \
        linux-headers \
    ; \
    \
    docker-php-ext-install pdo_mysql; \
    \
    apk del $PHPIZE_DEPS

# Clear cache
RUN rm -rf /var/cache/apk/*